# Generated by Django 4.0.2 on 2023-03-15 14:34

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='mobile_image/')),
                ('colors', multiselectfield.db.fields.MultiSelectField(choices=[('GREEN', 'green'), ('YELLOW', 'yellow'), ('BLUE', 'blue'), ('RED', 'red'), ('BROWN', 'brown'), ('WHITE', 'white'), ('BLACK', 'black')], max_length=200)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
