# Generated by Django 4.0.2 on 2023-03-15 14:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
