# Generated by Django 4.0.2 on 2023-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_mobile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='old_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
