# Generated by Django 4.0.2 on 2023-03-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mobile_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
