# Generated by Django 4.0.2 on 2023-03-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
