# Generated by Django 4.0.2 on 2023-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_mobile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
