# Generated by Django 4.0.2 on 2023-03-17 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_mobile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='book_image/')),
                ('price', models.PositiveIntegerField(default=0)),
                ('datetime_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
