# Generated by Django 4.0.2 on 2023-03-17 15:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comment_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
