# Generated by Django 4.0.2 on 2023-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_book_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='static/img/No-Image.jpg', upload_to='book_image/'),
        ),
    ]
