# Generated by Django 4.0.2 on 2023-03-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='name',
            new_name='title',
        ),
    ]
